### ISSUE TITLE
make runtest failed with MKL 2017 Beta Update 1

### ISSUE THREAD

**Issue by sato-cloudian** [intelcaffe/caffe#12]
Hi,

Thanks for pushing all those changes!!

I tried to build the latest intelcaffe with the MKL 2017 Beta Update1.
Successfully compiled, but got the following error at make runtest.

> $ git show
> commit 8fa113bac61fcb5c423dda2cd908a5ee589803bf
> Merge: 31c3a05 24b8109
> Author: Jacek Czaja <jacek.czaja@intel.com>
> Date:   Tue May 31 15:01:52 2016 +0200
> 
>     task-doc-minor-changes: - Minor changes in documentation
> 

**error log**

> [----------] 12 tests from SGDSolverTest/1, where TypeParam = caffe::CPUDevice<double>
> [ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithWeightDecayMultiIter
> [       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithWeightDecayMultiIter (232 ms)
> [ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithMomentum
> [       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithMomentum (62 ms)
> [ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateLROneHundredth
> [       OK ] SGDSolverTest/1.TestLeastSquaresUpdateLROneHundredth (32 ms)
> [ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithEverythingShare
> F0602 15:58:08.987087 31955 loss_layer.cpp:19] Check failed: bottom[0]->num() == bottom[1]->num() (2 vs. 4) The data and label should have the same number.
> *** Check failure stack trace: ***
>     @     0x2b72992a4daa  (unknown)
>     @     0x2b72992a4ce4  (unknown)
>     @     0x2b72992a46e6  (unknown)
>     @     0x2b72992a7687  (unknown)
>     @     0x2b729d9d6c50  caffe::LossLayer<>::Reshape()
>     @     0x2b729d9b8443  caffe::EuclideanLossLayer<>::Reshape()
>     @     0x2b729d90a915  caffe::Net<>::Init()
>     @     0x2b729d90b7c5  caffe::Net<>::Net()
>     @     0x2b729da20082  caffe::Solver<>::InitTrainNet()
>     @     0x2b729da20fbc  caffe::Solver<>::Init()
>     @     0x2b729da21348  caffe::Solver<>::Solver()
>     @     0x2b7298970ab4  caffe::SGDSolverTest<>::InitSolver()
>     @     0x2b7298972463  caffe::GradientBasedSolverTest<>::InitSolverFromProtoString()
>     @     0x2b7298942e7d  caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
>     @     0x2b72989467d9  caffe::GradientBasedSolverTest<>::TestLeastSquaresUpdate()
>     @     0x2b729896b7a8  caffe::SGDSolverTest_TestLeastSquaresUpdateWithEverythingShare_Test<>::TestBody()
>     @     0x2b7298cb9a43  testing::internal::HandleExceptionsInMethodIfSupported<>()
>     @     0x2b7298cafd87  testing::Test::Run()
>     @     0x2b7298cafe2e  testing::TestInfo::Run()
>     @     0x2b7298caff35  testing::TestCase::Run()
>     @     0x2b7298cb19a8  testing::internal::UnitTestImpl::RunAllTests()
>     @     0x2b7298cb1c64  testing::UnitTest::Run()
>     @     0x2b729891aec2  main
>     @     0x2b729e4c5ec5  (unknown)
>     @     0x2b7298927372  (unknown)
>     @              (nil)  (unknown)
> Aborted (core dumped)
> make: *** [runtest] Error 134

Do you have any idea how this could happen?

Thanks!

**Comment by jczaja** [comment]
Hi, thanks very much for report, we just hit this problem few hours before your report. We are working on it. will let you know as soon as it is fixed

**Comment by sato-cloudian** [comment]
OK, thanks.

**Comment by sato-cloudian** [comment]
I confirmed make runtest runs successfully with the latest one as follows.

> [----------] Global test environment tear-down
> [==========] 1088 tests from 154 test cases ran. (46240 ms total)
> [  PASSED  ] 1088 tests.
> 
>   YOU HAVE 4 DISABLED TESTS
> 

> $ git show
> commit 31ad350536718ad8de30ae5f4a33bffc61dd8574
> Merge: fa1f3c7 589be3a
> Author: jreniecki <jacek.reniecki@intel.com>
> Date:   Wed May 18 14:50:53 2016 +0200
> 
>     task-align-with-mkl2017-bu1-fixup-fixup: Trigger new pre-review build :)
>

**Comment by sato-cloudian** [comment]
I have tested on a beta installation instead of update 1.

make runtest still fails at the same test with the same error.

**Comment by jczaja** [comment]
there were 4 tests failing, we managed to fixed two of them. So we are halfway through.

Tests are failing when you build intelcaffe with a flag: USE_MKL2017_AS_DEFAULT_ENGINE . If you build without that flag then Unit tests will pass, but to take advantage of MKL2017 Beta you would have manually add engine attribute in model description. Example model is models/mkl2017_alexnet.
Reason behind this is MKL2017 focused on getting popular models working fast, leaving behind 
some of functionality not used in that models. 

So for now on, setting USE_MKL2017_AS_DEFAULT_ENGINE is still experimental path, until we will have gaps satisfied. We will let you know as soon as this is done.

**Comment by sato-cloudian** [comment]
Thanks, I confirmed make runtest succeeds without USE_MKL2017_AS_DEFAULT_ENGINE.

Manually adding engine parameter is fine.
